# Generated by Django 4.0.2 on 2022-02-25 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='The Title of the TODO')),
                ('content', models.TextField(verbose_name='The content of the Todo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
